language: node_js
node_js:
  - 10

cache:
  directories:
    - node_modules

script:
  - npm run lint:js
  - npm run lint:css
  - npm run build

notifications:
  email:
    on_success: never
    on_failure: never
