language: node_js
node_js:
  - 10

cache:
  yarn: true
  directories:
    - node_modules

script:
  - yarn lint:ts
  - yarn lint:css
  - yarn typecheck

notifications:
  email:
    on_success: never
    on_failure: never
